/* com_yassl_cyassl_TestCTaoCrypt.h
 *
 * Copyright (C) 2006-2011 Sawtooth Consulting Ltd.
 *
 * This file is part of CyaSSL.
 *
 * CyaSSL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * CyaSSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yassl_cyassl_TestCTaoCrypt */

#ifndef _Included_com_yassl_cyassl_TestCTaoCrypt
#define _Included_com_yassl_cyassl_TestCTaoCrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    testCtc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_testCtc
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    md5_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_md5_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    md4_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_md4_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    sha_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_sha_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    sha256_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_sha256_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    sha512_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_sha512_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    ripemd_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_ripemd_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    hmac_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_hmac_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    arc4_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_arc4_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    hc128_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_hc128_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    rabbit_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_rabbit_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    des_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_des_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    des3_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_des3_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    aes_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_aes_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    random_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_random_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    rsa_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_rsa_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    dh_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_dh_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    dsa_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_dsa_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    pwdbased_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_pwdbased_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    openssl_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_openssl_1test
  (JNIEnv *, jobject);

/*
 * Class:     com_yassl_cyassl_TestCTaoCrypt
 * Method:    ecc_test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yassl_cyassl_TestCTaoCrypt_ecc_1test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
